#! /bin/bash

# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of this
# software and associated documentation files (the "Software"), to deal in the Software
# without restriction, including without limitation the rights to use, copy, modify,
# merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
# PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

if [ -z "$THING_NAME" ]; then
  echo "THING_NAME is required"
  exit 0
fi

RUN_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

ACCOUNT_ID=$(aws --output text sts get-caller-identity --query 'Account')
MQTT_ENDPOINT=$(aws --output text iot describe-endpoint --endpoint-type iot:Data-ATS --query 'endpointAddress')

THING_POLICY_NAME=device-client-provisioner-policy
CERTS_DIR=$HOME/${THING_NAME}-certs
ROOT_CERT_PATH=${CERTS_DIR}/AmazonRootCA1.pem
DEVICE_CERT_PATH=${CERTS_DIR}/${THING_NAME}_thing.cert.pem
PUBLIC_KEY_PATH=${CERTS_DIR}/${THING_NAME}_thing.public.key
PRIVATE_KEY_PATH=${CERTS_DIR}/${THING_NAME}_thing.private.key
